name: PR Template Handler

on:
  pull_request:
    types: [labeled]

jobs:
  update-pr-description:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
    - name: Check out the repository
      uses: actions/checkout@v3

    - name: Update PR Description
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        LABEL_NAME="${{ github.event.label.name }}"
        PR_NUMBER="${{ github.event.pull_request.number }}"
        REPO="${{ github.repository }}"

        if [ "$LABEL_NAME" = "wizard" ]; then
          TEMPLATE_PATH=".github/templates/wizardTemplate.md"
        else
          exit 0
        fi

        PR_TEMPLATE=$(cat "$TEMPLATE_PATH")

        # Update the PR description using the GitHub API
        curl -X PATCH \
          --header "Authorization: token $GITHUB_TOKEN" \
          --header 'content-type: application/json' \
          --url "https://api.github.com/repos/$REPO/pulls/$PR_NUMBER" \
          -d "$(jq -n --arg body "$PR_TEMPLATE" '{body: $body}')"
